# fly.toml app configuration file generated for hidden-camera-sweep-in-restrooms on 2026-06-26T05:33:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hidden-camera-sweep-in-restrooms'
primary_region = 'nrt'

[build]

[env]
  FLASK_APP = 'app.py'
  FLASK_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
