"""add photos column

Revision ID: e962d33b72bc
Revises: f7a0e1c7fcf9
Create Date: 2026-06-26 05:26:18.169029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e962d33b72bc'
down_revision = 'f7a0e1c7fcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
