"""toss-redesign-v3

Revision ID: f7a0e1c7fcf9
Revises: 
Create Date: 2026-06-26 05:12:05.751827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a0e1c7fcf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restroom_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=2), nullable=False),
    sa.Column('inspector_name', sa.String(length=100), nullable=True),
    sa.Column('before_photo', sa.Text(), nullable=True),
    sa.Column('after_photo', sa.Text(), nullable=True),
    sa.Column('photo_lat', sa.Float(), nullable=True),
    sa.Column('photo_lng', sa.Float(), nullable=True),
    sa.Column('chk_partition', sa.Boolean(), nullable=True),
    sa.Column('chk_ceiling', sa.Boolean(), nullable=True),
    sa.Column('chk_drain', sa.Boolean(), nullable=True),
    sa.Column('chk_outlet', sa.Boolean(), nullable=True),
    sa.Column('chk_trash', sa.Boolean(), nullable=True),
    sa.Column('chk_fixture', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.Boolean(), nullable=True),
    sa.Column('action_detail', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restroom_id'], ['restrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspections')
    op.drop_table('restrooms')
    op.drop_table('buildings')
    # ### end Alembic commands ###
